import "./styles.css"
import {Todo} from "./components/todo/todo"
import { Project } from "./components/project/project"
import { ProjectList } from "./components/projectList/projectList"
import "./controller"